apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdproject
  labels:
    app: cicdproject
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cicdproject
  template:
    metadata:
      labels:
        app: cicdproject
    spec:
      containers:
        - name: cicdproject
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}